// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LightNap.Scaffolding.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\Scaffolding\LightNap.Scaffolding\Templates\Front-End\Area\Components\Pages\Create\CreateHtml.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CreateHtml : LightNap.Scaffolding.Templates.BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"
<p-card header=""Create"">
  <div class=""flex gap-1 mb-1"">
    <p-button [routerLink]=""['..']"" icon=""pi pi-arrow-up"" label=""Up to all"" />
  </div>

  <form [formGroup]=""form"" (ngSubmit)=""createClicked()"" autocomplete=""off"">
    <div class=""flex flex-column gap-1"">
      <textarea rows=""10"" cols=""30"" pInputTextarea formControlName=""json""></textarea>

      <error-list [errors]=""errors"" />
      <p-button type=""submit"" label=""Create"" icon=""pi pi-plus"" severity=""success"" [disabled]=""!form.valid"" />
    </div>
  </form>
</p-card>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
